<a href="https://colab.research.google.com/github/sohilvhora0/Assignment-Python-Data-Structure/blob/main/Numpy_Assignemnt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

import numpy as np
arr=np.arange(0,5)
print(arr)
print(type(arr))

[0 1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
#2. Given a NumPy array 'arr', check if its data type is float64.

import numpy as np

arr = np.array([1.5, 2.6, 3.7])

print("data type:",arr.dtype)
print("yes its float64")

data type: float64
yes its float64


In [6]:
#3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

import numpy as np
arr=np.array([5+6j,7+5j,10+7j])

print("data type:",arr.dtype)

data type: complex128


In [7]:
#4. Convert an existing NumPy array 'arr' of integers to float32 data type.

import numpy as np
arr=np.array([1,2])

float_array=np.array(arr, dtype=np.float32)

print(float_array)
print(float_array.dtype)

[1. 2.]
float32


In [8]:
#5.Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

import numpy as np

arr=np.array([1.9,2.7,3.4])

print(arr.dtype)

reduce=np.array(arr, dtype=np.float32)

print("after reducing decimal:",reduce.dtype)

float64
after reducing decimal: float32


In [9]:
#6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and datatype.

import numpy as np
array_att1= np.array([[4,5],[4,3],[4,4]])

def array_attributes(array_att1):
    a=array_att1.shape
    b=array_att1.size
    c=array_att1.dtype
    return a,b,c

print("shape , size and data type:",array_attributes(array_att1))

shape , size and data type: ((3, 2), 6, dtype('int64'))


In [10]:
#7 Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

import numpy as np

arr=np.array([[4,5],[5,6]])

def array_dimension(arr):
    a=arr.ndim
    return a
print("dimension is:",array_dimension(arr))

dimension is: 2


In [11]:
#8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

import numpy as np
arr= np.array([4,5,6,7,8,9,10])
def item_size_info(arr):
    a= arr.itemsize
    b= arr.nbytes
    return a, b

print("here the item size and total size in bytes:",item_size_info(arr))

here the item size and total size in bytes: (8, 56)


In [12]:
#9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.


import numpy as np

arr= np.arange(0,10)

def array_strides(arr):
    return arr.strides

print("strides of the array:",array_strides(arr))

strides of the array: (8,)


In [13]:
# 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

import numpy as np


arr=np.array([1,2,3,4,5,6,7,8,9,10])

def function_shape_strides_relationship(arr):
    a=arr.size
    b=arr.strides
    return a,b

print("size and strides:",function_shape_strides_relationship(arr))

size and strides: (10, (8,))


In [16]:
#11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.

import numpy as np

n=int(input("enter the number for create_zeros_array"))

def create_zeros_array(n):
    return np.zeros(n)

print(create_zeros_array(n))

enter the number for create_zeros_array10
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [17]:
# 12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D
# NumPy array filled with ones of size `rows x cols`.

import numpy as np
row=int(input("enter the number for row"))
cols=int(input("enter the number for columns"))

def create_ones_matrix(row,cols):
    return np.ones((row,cols))


print(create_ones_matrix(row,cols))

enter the number for row15
enter the number for columns15
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [19]:
# 13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
#creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`.
import numpy as np


start=int(input("enter the start num"))
stop= int(input("enter the num where u want to stop"))
step=int(input("enter the step num"))


def generate_range_array(start,stop,step):
    return np.arange(start,stop,step)

print(generate_range_array(start,stop,step))


enter the start num0
enter the num where u want to stop10
enter the step num5
[0 5]


In [20]:
#14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
#arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).

import numpy as np

def generate_linear_space(start:float, stop:float, num:int):
    return np.linspace(start, stop, num)

print(generate_linear_space(0,12.5,5))

[ 0.     3.125  6.25   9.375 12.5  ]


In [22]:
# 15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
#identity matrix of size `n x n` using `numpy.eye`

import numpy as np

n=int(input("enter the number"))

def create_identity_matrix(n):
    return np.eye(n,n,dtype=int)

print(create_identity_matrix(n))

#insight- np.eye() Returns a 2-D array with ones on the diagonal and zeros elsewhere.

enter the number10
[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]


In [23]:
#16. Write a function that takes a Python list and converts it into a NumPy array.

import numpy as np

lis=[4,5,6,7,8,9,10]

def lis_to_nump_arr(lis):
    return np.array(lis)

print(lis_to_nump_arr(lis))

[ 4  5  6  7  8  9 10]


In [24]:
#17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.


import numpy as np

#original array
org_array= np.array([1,2,3,4,5])

print("orginal data:", org_array)

#use numpy.view()  to create a new object with same data
view_array= org_array.view()

print("view array:", view_array)

#let's modify the original data

org_array[0] = 101

print("modified original data:",org_array)
#view array will modified bc its shares the same data


print("view array after original data modification:",view_array)

orginal data: [1 2 3 4 5]
view array: [1 2 3 4 5]
modified original data: [101   2   3   4   5]
view array after original data modification: [101   2   3   4   5]


In [25]:
#18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

import numpy as np

def concatenate_arrays(arr1, arr2, axis):
        return np.concatenate((arr1, arr2), axis)

arr1= np.array([4,5,6])
arr2=np.array([7,8,9])


#1d array
print(concatenate_arrays(arr1,arr2, axis=0))
#2d array with 1 axis


arr1= np.array([[4,5,6],[7,8,9]])
arr2=np.array([[10,11],[12,13]])
print()

print(concatenate_arrays(arr1, arr2, axis=1))

[4 5 6 7 8 9]

[[ 4  5  6 10 11]
 [ 7  8  9 12 13]]


In [26]:
# 19.  Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy. concatenate`.

import numpy as np


num1= np.array([[3,3],[4,4]])
num2= np.array([[5,5,5],[6,6,6]])

horizontally= np.concatenate((num1,num2), axis=1)

print(horizontally)

[[3 3 5 5 5]
 [4 4 6 6 6]]


In [27]:
#20. Write a function that vertically stacks multiple NumPy arrays given as a list.

import numpy as np

def vertical_array(arrays):
    return np.vstack(arrays)

arrays=  [np.array([1,2,3,4,5]), np.array([6,7,8,9,10]), np.array([11,12,13,14,15])]




print(vertical_array(arrays))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [28]:
# 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive)
#with a given step size.


import numpy as np


def array_int(start, end, step):
    return np.arange(start,end+1,step)



print(array_int(1,20,3))

[ 1  4  7 10 13 16 19]


In [29]:
#22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

import numpy as np

def generate_array():
    return np.linspace(0,1,10)

print(generate_array())

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [30]:
# 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

import numpy as np

def log_spaced_values(start, end, num_values):
    return np.logspace(np.log10(start), np.log10(end)+1, num_values,base=5)

values=log_spaced_values(1,1000,5)

print(values)

[  1.   5.  25. 125. 625.]


In [31]:
# 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values
# are random integers between 1 and 100.

import pandas as pd
import numpy as np


arr=np.random.randint(1,100,(5,3))


df= pd.DataFrame(arr, columns=['column1','column2','column3'])

print(df)

   column1  column2  column3
0       22       61       62
1        8       78       77
2       59       96        3
3       82       94       76
4       35       73       86


In [32]:
#25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column
#with zeros. Use NumPy operations within the Pandas DataFrame.

import pandas as pd
import numpy as np

def replace_neg_values(df, column1):
    df[column1]= np.where(df[column1] <0,0, df[column1])
    return df


df=pd.DataFrame({'a':[1,2,3,-4,-8], 'b':[7,10,20,30,40]})
print(df)
print("after modification")

res= replace_neg_values(df, 'a')

print(res)

   a   b
0  1   7
1  2  10
2  3  20
3 -4  30
4 -8  40
after modification
   a   b
0  1   7
1  2  10
2  3  20
3  0  30
4  0  40


In [33]:
#26. Access the 3rd element from the given NumPy array.

import numpy as np
arr = np.array([10, 20, 30, 40, 50])


arr[2]

30

In [34]:
# 27. Retrieve the element at index (1, 2) from the 2D NumPy array.

import numpy as np

arr_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])


#element at index (1, 2)
arr=arr_2d[1,2]
print(arr)

6


In [35]:
#28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.

import numpy as np
arr = np.array([3, 8, 2, 10, 5, 7])

arr[0]=3.0
arr

res=np.extract(arr > 5 ,arr)

print(res)
print()
#another method to extract

res1= arr[arr>5]

print(res1)

[ 8 10  7]

[ 8 10  7]


In [36]:
#29 Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])


slicing= arr[2:6]
print(slicing)

[3 4 5 6]


In [37]:
# 30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.

import numpy as np
arr_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(arr_2d)

print()

print("below the sub array ")
sub_array=arr_2d[0:2,1:3]

#second method for the same
sub_array=arr_2d[0:2,[1,2]]



print(sub_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

below the sub array 
[[2 3]
 [5 6]]


In [47]:
#31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.

import numpy as np

arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

# Define the indices to extract
indices = np.array([0, 1, 2])  # Example indices

def extract_ele(arr, indices):
    """
    Extracts elements from a 2D array in a specific order based on given indices.

    Args:
    arr (NumPy array): The input 2D array.
    indices (NumPy array): Array containing the indices to extract.

    Returns:
    tuple: A tuple containing the extracted elements.
    """
    a=arr[0, indices[0]] # Access elements using the provided indices
    b=arr[1, indices[1]]
    c=arr[2, indices[2]]
    return a,b,c


res=extract_ele(arr, indices)

print(res)

(1, 5, 9)


In [48]:
#32.Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

import numpy as np

arr=np.array([1,2,3,4,5,6,7,8,9,10,11])
threshold= 5

def filter_ele(arr, threshold):
    return arr[arr > threshold]

res=filter_ele(arr,threshold)

print(res)

[ 6  7  8  9 10 11]


In [49]:
#33.Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three
#separate arrays for each dimension.


import numpy as np

arr=np.array([[[1,2,3],[4,5,6],[7,8,9]],
               [[10,11,12],[13,14,15],[16,17,18]],
               [[19,20,21],[22,23,24],[25,26,27]]])

def sep_array(arr):
    ind1=arr[0,1,2]
    ind2=arr[1,2,0]
    ind3=arr[2,1,0]
    return ind1,ind2,ind3

res=sep_array(arr)
print(res)

(6, 16, 22)


In [50]:
# 34.Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.
import numpy as np

arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,15])

def numpy_fun(arr, condition1, condition2):
    return arr[condition1 & condition2]



condition1= arr > 4
condition2= arr < 12

res= numpy_fun(arr, condition1, condition2)
print(res)

[ 5  6  7  8  9 10 11]


In [53]:
# 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

import numpy as np

def arr_indices(arr, row_num,col_num):
    return arr[row_num,col_num]

arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

row_num= np.array([0,2])
col_num=np.array([1,0])

newarray= arr_indices(arr, row_num,col_num)

print(newarray)

[2 7]


In [54]:
#36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

import numpy as np

arr=np.random.randint(1,10,(3,3))

print(arr)

print()
print("add a scalar value of 5 to each element using NumPy broadcasting:")

a= arr + 5
print(a)

[[8 3 4]
 [1 5 7]
 [1 3 7]]

add a scalar value of 5 to each element using NumPy broadcasting:
[[13  8  9]
 [ 6 10 12]
 [ 6  8 12]]


In [55]:
# 37.Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
#corresponding element in arr1 using NumPy broadcasting.

import numpy as np

arr1=np.array([[1,2,3]]) # shape(1,3)
arr2=np.array([[4,5,6,7],[8,9,10,11],[12,13,14,15]])  #shpae(3,4)

res= arr2 * arr1[:,:,np.newaxis]
print(res)


[[[ 4  5  6  7]
  [16 18 20 22]
  [36 39 42 45]]]


In [56]:
#38.Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

import numpy as np

arr1= np.array([1,2,3,4])
arr2=np.array([[4,5,6],[7,8,9],[10,11,12],[13,14,15]])

res= arr2 +arr1[:,np.newaxis]

print(res)

[[ 5  6  7]
 [ 9 10 11]
 [13 14 15]
 [17 18 19]]


In [57]:
#39.Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.
import numpy as np

arr1=np.array([[1],[2],[3]])  #shape(3,1)
arr2=np.array([4,5,6])         #shape(1,3)


arr1 +arr2

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [58]:
#40.Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
# broadcasting. Handle the shape incompatibility.

import numpy as np

arr1= np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8],[9,10]])

arr2=arr2.reshape(2,2,1)    #now shape is become 2,2,1

res= arr1 * arr2

print(res)

[[[ 7 14 21]
  [32 40 48]]

 [[ 9 18 27]
  [40 50 60]]]


In [59]:
#41. Calculate column-wise mean for the given array:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])


a=np.mean(arr, axis=0)
print(a)

[2.5 3.5 4.5]


In [60]:
#42. Find maximum value in each row of the given array:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

np.max(arr,axis=1)

array([3, 6])

In [61]:
#43. For the given array, find indices of maximum value in each column.

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

np.max(arr,axis=0)

array([4, 5, 6])

In [62]:
#44. For the given array, apply custom function to calculate moving sum along rows.

import numpy as np


arr = np.array([[1, 2, 3], [4, 5, 6]])

def moving_sum(arr):
    result=[]
    for j in arr:
        res=[]
        for i in range(len(j)-1):
            sum_row=sum(j[i:i+2])
            res.append(sum_row)
        result.append(res)
    return np.array(result)

print(moving_sum(arr))

[[ 3  5]
 [ 9 11]]


In [63]:
# 45. In the given array, check if all elements in each column are even.

import numpy as np

arr = np.array([[2, 4, 6], [3, 5, 7]])



print("even elements:")
even=arr[arr %2==0]
print(even)

even elements:
[2 4 6]


In [64]:
#46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.

import numpy as np

original_array = np.array([1, 2, 3, 4, 5, 6])

def reshape_array(original_array, m,n):
    return original_array.reshape((m,n))

m=2
n=3
reshape=reshape_array(original_array, m,n)
print(reshape)

[[1 2 3]
 [4 5 6]]


In [65]:
#47. Create a function that takes a matrix as input and returns the flattened array.


import numpy as np

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

def mat_arr(input_matrix):
    return input_matrix.flatten()

flatten=mat_arr(input_matrix)

print(flatten)

[1 2 3 4 5 6]


In [66]:
#48. Write a function that concatenates two given arrays along a specified axis.

import numpy as np

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])


def concatenates_func(array1, array2):
    return np.concatenate((array1,array2), axis=1)

res= concatenates_func(array1, array2)

print(res)

[[1 2 5 6]
 [3 4 7 8]]


In [67]:
#49.Create a function that splits an array into multiple sub-arrays along a specified axis.

import numpy as np


original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

def split_func(original_array):
    return np.split(original_array, 3, axis=0)


res=split_func(original_array)
print(res)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [68]:
#50. Write a function that inserts and then deletes elements from a given array at specified indices.

import numpy as np


original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

def insert_delete_elements(array, indices_to_insert, values_to_insert, indices_to_delete):

    # Convert the input array to a list for easier manipulation
    array_list = array.tolist()

    # Insert elements at specified indices
    for idx, val in zip(indices_to_insert, values_to_insert):
        array_list.insert(idx, val)

    # Delete elements at specified indices
    for idx in sorted(indices_to_delete, reverse=True):
        del array_list[idx]

    # Convert the list back to a NumPy array
    modified_array = np.array(array_list)

    return modified_array


modified_array = insert_delete_elements( original_array,indices_to_insert, values_to_insert, indices_to_delete)
print(modified_array)

[ 1 10 11  4  5]


In [69]:
#51.Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
#Perform element-wise addition between `arr1` and `arr2`.

import numpy as np

arr1=np.random.randint(1,10,(10))
print(arr1)
arr2=np.array([1,2,3,4,5,6,7,8,9,10])

arr1 +arr2

[5 6 3 2 4 6 8 2 6 2]


array([ 6,  8,  6,  6,  9, 12, 15, 10, 15, 12])

In [70]:
#52 Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
#from 1 to 10. Subtract `arr2` from `arr1` element-wise.


import numpy as np

arr1=np.array([10,9,8,7,6,5,4,3,2,1])
arr2=np.array([1,2,3,4,5,6,7,8,9,10])

arr2 - arr1

array([-9, -7, -5, -3, -1,  1,  3,  5,  7,  9])

In [71]:
# 53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
#Perform element-wise multiplication between `arr1` and `arr2`.


import numpy as np

arr1=np.random.randint(1,5,5)
print(arr1)
print()

arr2=np.array([1,2,3,4,5])

arr1 *arr2

[4 1 4 3 2]



array([ 4,  2, 12, 12, 10])

In [72]:
#54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
#to 5. Perform element-wise division of `arr1` by `arr2`

import numpy as np

arr1=np.array([2,4,6,8,10])

arr2= np.array([1,2,3,4,5])


arr1 / arr2

array([2., 2., 2., 2., 2.])

In [73]:
#55.Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
#reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.


import numpy as np

arr1= np.array([1,2,3,4,5])
arr2=np.array([5,4,3,2,1])

exp_power=np.power(arr1,arr2)

print("arr1:",arr1)
print("arr2",arr2)
print("exp_power:", exp_power)

arr1: [1 2 3 4 5]
arr2 [5 4 3 2 1]
exp_power: [ 1 16 27 16  5]


In [74]:
#56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.

import numpy as np

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])


def count_sub_array(arr, substring):

    list_arr=arr.tolist()  # convert into list
    count=0
    for i in list_arr:
        if substring in i:
            count+=1
    return count

hello_substring=  count_sub_array(arr, "hello")

print("hello: " ,hello_substring)

world_substring=count_sub_array(arr, "world")

print("world:", world_substring)


hello:  3
world: 1


In [75]:
#57.Write a function that extracts uppercase characters from a NumPy array of strings.


import numpy as np

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])



def uppercase_char(arr):
    return np.char.upper(arr)

uppercase=uppercase_char(arr)
print(uppercase)

['HELLO' 'WORLD' 'OPENAI' 'GPT']


In [76]:
#58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.


import numpy as np



def replace_substring(strings, old_substring, new_substring):
    strings= np.asarray(strings, dtype=str)
    replace_func=np.vectorize(lambda x : x.replace(old_substring, new_substring))
    return replace_func(strings)

strings = np.array(['apple box', 'banana box', 'grape box', 'pineapple box'])
new_string= replace_substring(strings, "box","pieces" )

print(new_string)

['apple pieces' 'banana pieces' 'grape pieces' 'pineapple pieces']


In [77]:
# 59. Write a function that concatenates strings in a NumPy array element-wise.

import numpy as np

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

def concatenates(arr1,arr2):
    return np.concatenate((arr1,arr2), axis=0)


res= concatenates(arr1,arr2)
print(res)

['Hello' 'World' 'Open' 'AI']


In [78]:
#60.Write a function that finds the length of the longest string in a NumPy array.

import numpy as np



arr = np.array(['apple', 'banana', 'grape', 'pineapple'])


def longest_str_lenth(array):

    array=np.asarray(array, dtype=str)
    string_len=np.vectorize(len)(array)
    return np.max(string_len)

strings = np.array(['apple', 'banana', 'grape', 'pineapple'])


longest_len= longest_str_lenth(strings)
print("length of the longest string is:", longest_len)

length of the longest string is: 9


In [79]:
#61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
#standard deviation of the dataset using NumPy's functions.

import numpy as np


data= np.random.randint(1,1001,100)

print(data)
print()
mean=np.mean(data)
print("mean:",mean)

median= np.median(data)
print("median:", median)

variance= np.var(data)
print("variance:", variance)

std=np.std(data)
print("standard daviation:", std)

[845 772 193 862 233 454 344 665 458 308 209 854 565 745 687 636 138 290
 948 699 946 207 691 378 256 804 540 259 498   8 202 538 558 920 326 918
  65 627 359 703 197 967 700 937 584 940 727 748 617 875 189 766 618 449
 237 561 184 435 747 274 296 435 745 784 557 949 508 575 409 523 965 181
 725 328 993 828 808 655 280 926 657 502 242 169 437 119  31 418 339 927
 490 430 828 950 415 986 643 814 963 333]

mean: 556.23
median: 559.5
variance: 72302.0571
standard daviation: 268.8904183863754


In [80]:
#62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

import numpy as np

arr= np.random.randint(1,101,50)
print(arr)
print()

percentiles= np.percentile(arr,[25,75])

print('25th percentile:', percentiles[0])
print('75th percentile:',percentiles[1])

[ 41  79  79  92  97  79  70  27   4  39  11   5  14  37  36 100   2  89
  25  33  71  78  56  89  87  54   1  58  91  49  13 100  66  16  47  89
  81  68  94   1  76   5  33  33  44  96  22  36  60  98]

25th percentile: 28.5
75th percentile: 80.5


In [81]:
#63.Create two arrays representing two sets of variables. Compute the correlation coefficient between these
#arrays using NumPy's `corrcoef` function.

import numpy as np

a=np.array([1,12,14,16,18,20])
b=np.array([21,22,24,26,28,30])

corr_coff=np.corrcoef(a,b)[0,1]

print("correlation coefficien:",corr_coff)

correlation coefficien: 0.8712892542803548


In [82]:
#64.Create two matrices and perform matrix multiplication using NumPy's `dot` function.

import numpy as np

a=np.array([[1,2,3],[4,5,6]])  # shape(2,3)
b=np.array([[1,2],[3,4],[5,6]])  #shape(3,2)


c= np.dot(a, b)

print("matrix a:")
print(a)
print("matrix b:")
print(b)

print("matrix multiplication:")
print(c)

matrix a:
[[1 2 3]
 [4 5 6]]
matrix b:
[[1 2]
 [3 4]
 [5 6]]
matrix multiplication:
[[22 28]
 [49 64]]


In [83]:
#65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th
#percentiles along with the first and third quartiles

import numpy as np

arr=np.random.randint(10,1001,50)

#calculate the 10th,50th(mnedian), and 90th percentile
p10=np.percentile(arr, 10)
p50=np.percentile(arr,50)
p90=np.percentile(arr,90)

#calculate the first and third quartiles

q1=np.percentile(arr,25)
q3=np.percentile(arr,75)

print('original array:')
print(arr)
print("percentiles and quartiles")
print("10th percentile:", p10)
print("50th percentile:",p50)
print('90th percentile:',p90)
print("1st quartiles:",q1)
print("3rd qaurtiles:",q3)

original array:
[878 857 236 936 521 162 678 357 561 326 479 382 131 499 720 601 235 108
  44 876 445 187 682 715 875 624 690 818 758 860 475  45 991 739 955 308
 137 398 670  67 522  18 593 894 800 495 744 702  85 117]
percentiles and quartiles
10th percentile: 105.7
50th percentile: 541.5
90th percentile: 876.2
1st quartiles: 254.0
3rd qaurtiles: 742.75


In [84]:
#66.Create a NumPy array of integers and find the index of a specific element.

import numpy as np

arr=np.array([[1,2,3],
              [4,5,6,],
              [7,8,9]])

print(arr)

#find the index of 5,4

a=np.where(arr==5)
print(a)
b=np.where(arr==4)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(array([1]), array([1]))
(array([1]), array([0]))


In [85]:
#67. Generate a random NumPy array and sort it in ascending order

import numpy as np

arr=np.random.randint(1,10,10)

print(arr)

#sorted in ascending order
sort=np.sort(arr)
print("after sorted in ascending order:")
print(sort)

[2 2 5 9 8 7 7 4 3 3]
after sorted in ascending order:
[2 2 3 3 4 5 7 7 8 9]


In [86]:
#68. Filter elements >20  in the given NumPy array.


import numpy as np

arr = np.array([12, 25, 6, 42, 8, 30])

#filter elements > 20
a= arr[arr > 20]
print(a)

[25 42 30]


In [87]:
#69. Filter elements which are divisible by 3 from a given NumPy array.

import numpy as np

arr = np.array([1, 5, 8, 12, 15])

for i in arr:
    if i %3==0:
        print(i)

#another method

filtered=arr[arr %3==0]

print(filtered)

12
15
[12 15]


In [88]:
#70.. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.

import numpy as np

arr = np.array([10, 20, 30, 40, 50])

filtered=arr[ (arr >=20) &(arr <=40)]

print(filtered)

[20 30 40]


In [89]:
#71.For the given NumPy array, check its byte order using the `dtype` attribute byteorder.

import numpy as np

arr = np.array([1, 2, 3])

print(arr.dtype)

#check byteorder of the array

byte_order= arr.dtype.byteorder

print("byte order:", byte_order)

int64
byte order: =


In [90]:
#72.For the given NumPy array, perform byte swapping in place using `byteswap()`.

import numpy as np


arr = np.array([1, 2, 3], dtype=np.int32)
print("original array:", arr)
#performing byteswap in place
byteswap=arr.byteswap()
print("after byteswapping:",byteswap)

original array: [1 2 3]
after byteswapping: [16777216 33554432 50331648]


In [91]:
#73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.

import numpy as np


arr = np.array([1, 2, 3], dtype=np.int32)

#without modifying using newbyteorder()
arr2= arr.view(arr.dtype.newbyteorder())

print("org array:",arr)
print("after modify:", arr2)

org array: [1 2 3]
after modify: [16777216 33554432 50331648]


In [92]:
#74. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.

import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

#check the system endiannes

swapped_arr=arr.newbyteorder('>')  # big-endian
print(swapped_arr)

[16777216 33554432 50331648]


In [93]:
#75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.

import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

#checking byte swapping necessary
if arr.dtype.byteorder == "=":
    print("No byte swapping is necessary, the array byte native to the system")
elif arr.dtype.byteorder == "<":
    print("byte swapping is necessary bcs its little endian")
elif arr.dtype.byteorder==">":
    print("byte swapping is nexessary bcs its big-endian")

No byte swapping is necessary, the array byte native to the system


In [94]:
#76.Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
#an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`

import numpy as np

#Create a NumPy array `arr1` with values from 1 to 10.
arr1= np.array([1,2,3,4,5,6,7,8,9,10])

print("arr1 values from 1 to 10:",arr1)
#Create a copy of `arr1` named `copy_arr`
copy_arr=arr1.copy()
print("copy of arr1:",copy_arr)
#modifying an element in `copy_arr`
modify=copy_arr[2]=50

print("after modification in copy_arr:")
print(copy_arr)
print()

print("original array after modifying in copy:")
print(arr1)

arr1 values from 1 to 10: [ 1  2  3  4  5  6  7  8  9 10]
copy of arr1: [ 1  2  3  4  5  6  7  8  9 10]
after modification in copy_arr:
[ 1  2 50  4  5  6  7  8  9 10]

original array after modifying in copy:
[ 1  2  3  4  5  6  7  8  9 10]


In [95]:
#77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
#the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

import numpy as np

matrix= np.random.randint(1,10,(3,3))
print('original matrix:')
print(matrix)
print()

view_slice= matrix[1:,:1]
print("view slice:")
print(view_slice)
print()

#modiy element

view_slice[0,0]= 500
print('modify view slice:')
print(view_slice)
print()

#checking the original matrix changed or not

print("checking that,after modify in view slice original matrix:")
print(matrix)

original matrix:
[[4 9 7]
 [1 6 7]
 [2 4 1]]

view slice:
[[1]
 [2]]

modify view slice:
[[500]
 [  2]]

checking that,after modify in view slice original matrix:
[[  4   9   7]
 [500   6   7]
 [  2   4   1]]


In [96]:
#78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
#`view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`

import numpy as np

array_a= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

print("NumPy array `array_a` of shape (4, 3):")
print(array_a)
print()

#extract a slice

view_b= array_a[2:,:3]
print("Extracted a slice:")
print(view_b)
print()

#broadcast the addition of 5 to view_b

broadcast= view_b +5
print("broadcast the addition of 5 to view_b:")
print(broadcast)
print()


print("checking the alters the original `array_a`")
print(array_a)

NumPy array `array_a` of shape (4, 3):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Extracted a slice:
[[ 7  8  9]
 [10 11 12]]

broadcast the addition of 5 to view_b:
[[12 13 14]
 [15 16 17]]

checking the alters the original `array_a`
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [97]:
#79.Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
#`reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
#reflects changes in the original `orig_array`

import numpy as np

arig_array=np.array([[1,2,3,4],[5,6,7,8]])

print("orig_array` of shape (2, 4) with values from 1 to 8:")
print(arig_array)
print()


reshape_view= arig_array.reshape(4,2)

print("create reshaped_view` of shape (4, 2):")
print(reshape_view)
print()

#Modify an element in `reshaped_view`
reshape_view[3,1]=50

print("reshape_view after modification:")
print(reshape_view)
print()

#checking reflects changes in the original `orig_array
print("original arig_array:")
print(arig_array)

orig_array` of shape (2, 4) with values from 1 to 8:
[[1 2 3 4]
 [5 6 7 8]]

create reshaped_view` of shape (4, 2):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

reshape_view after modification:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7 50]]

original arig_array:
[[ 1  2  3  4]
 [ 5  6  7 50]]


In [98]:
# 80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
#elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.


import numpy as np

data= np.random.randint(0,20,(3,4))
print("data:")
print(data)
print()
#Extract a copy `data_copy` of elements greater than 5.

data_copy= data[data.copy()  > 5]
print("data copy of greater than 5")
print(data_copy)
print()

#Modify an element in `data_copy`

data_copy[2]= 50
print("after modify the data copy:")
print(data_copy)
print()

#verify if it affects the original `data
print("verify if it affects the original `data")
print("original data:")
print(data)
print()
print("copy data:")
print(data_copy)

data:
[[ 6 13 10 11]
 [ 0  2 17  0]
 [ 6 19  7 10]]

data copy of greater than 5
[ 6 13 10 11 17  6 19  7 10]

after modify the data copy:
[ 6 13 50 11 17  6 19  7 10]

verify if it affects the original `data
original data:
[[ 6 13 10 11]
 [ 0  2 17  0]
 [ 6 19  7 10]]

copy data:
[ 6 13 50 11 17  6 19  7 10]


In [99]:
# 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

import numpy as np

#Create two matrices A and B of identical shape containing integers
a= np.random.randint(1,10,(3,3))
b=np.random.randint(1,10,(3,3))

print("a:",a)
print()
print("b:",b)


#addition operation:
print("addition operation between a and b:")
addition= a + b
print(addition)

#subtraction operation:
print("subtraction operation between a and b:")
sub= a-b
print(sub)

a: [[1 7 5]
 [8 4 3]
 [4 1 3]]

b: [[9 4 1]
 [8 9 1]
 [6 5 5]]
addition operation between a and b:
[[10 11  6]
 [16 13  4]
 [10  6  8]]
subtraction operation between a and b:
[[-8  3  4]
 [ 0 -5  2]
 [-2 -4 -2]]


In [100]:
# 82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication

import numpy as np

c= np.random.randint(1,10,(3,2))  #shape (3,2)
d= np.random.randint(1,10,(2,4))    #shape (2,4)

print("two matrices")
print("c:")
print(c)
print()
print("d:")
print(d)
print()

#perform matrix multiplication
print("matrix multiplication of c and d:")

matrix_multp=np.dot(c,d)

print(matrix_multp)

two matrices
c:
[[1 6]
 [9 9]
 [1 4]]

d:
[[2 8 9 2]
 [6 7 1 7]]

matrix multiplication of c and d:
[[ 38  50  15  44]
 [ 72 135  90  81]
 [ 26  36  13  30]]


In [101]:
#83. Create a matrix `E` and find its transpose.

import numpy as np


#Create a matrix `E`.
E= np.random.randint(1,10,(3,3))
print("E:")
print(E)

#find its transpose.

transpose=E.T
print("transpose:")
print(transpose)

E:
[[6 3 5]
 [9 6 5]
 [8 3 5]]
transpose:
[[6 9 8]
 [3 6 3]
 [5 5 5]]


In [102]:
#84.Generate a square matrix `F` and compute its determinant.

import numpy as np



#Generate a square matrix `F`

F= np.random.randint(1,11,(3,3))
print("F:")
print(F)
print()

#compute its determinant.

determinant_F= np.linalg.det(F)
print("determinant of F:")
print(determinant_F)

F:
[[ 2  4 10]
 [10  7 10]
 [ 5  3  6]]

determinant of F:
-66.00000000000003


In [103]:
#85.Create a square matrix `G` and find its inverse

import numpy as np

G= np.random.randint(1,11,(4,4))

# find its inverse

inv= np.linalg.inv(G)

print("G:")
print(G)
print()
print("inverse of G:")
print(inv)

G:
[[ 3 10 10  6]
 [ 4  4  4  1]
 [ 8  7  6  9]
 [ 3 10  2  6]]

inverse of G:
[[-0.12557604  0.22119816  0.06451613 -0.00806452]
 [-0.00806452  0.09677419 -0.09677419  0.13709677]
 [ 0.125      -0.         -0.         -0.125     ]
 [ 0.03456221 -0.2718894   0.12903226 -0.01612903]]
